document.writeln("<html><head><meta http-equiv=\"Content-Type\" content=\"text\/html; charset=utf-8\">");
document.writeln("<title>title<\/title><base target=\"_blank\">");
document.writeln("<style type=\"text\/css\">");
document.writeln(" .clearfix:after{content:\".\";display:block;height:0;clear:both;visibility:hidden;}.clearfix{display:inline-block;}* html .clearfix{height:1%;}.clearfix{display:block;}body,h1,h2,h3,h4,h5,h6,dl,dt,dd,ul,ol,li,th,td,p,blockquote,pre,form,fieldset,legend,input,button,textarea,hr{margin:0;padding:0;}li{list-style:none;}body,button,input,select,textarea{font:12px\/1.125 Tahoma,Helvetica,\"宋体\",san-serif;color:#000;}a{color:#00009C;text-decoration:none;}a:hover{color:#f60;text-decoration:underline;}img{border:0px;}.JDimgList{float:left;padding:10px 0 5px;}.JDimgList li{display:inline;float:left;margin:0 0 2px 28px;overflow:hidden;width:124px;}.JDimgList .JDfoot{margin-top:11px;}.JDimgList li p{cursor:pointer;height:18px;line-height:18px;text-align:center;}.JDimgList li img{border:1px solid #CCCCCC;display:block;}.JDcontent{float:left;height:228px;overflow:hidden;padding:8px 0 0;}.JDcontent li{display:inline;float:left;margin:0 0 10px 28px;overflow:hidden;width:142px;}.JDcontent li a{display:block;height:21px;line-height:21px;padding-left:10px;overflow:hidden;width:142px;}.JDimgList{width:618px;}.JDimgList li{margin:0 0 0 28px;}.JDcontent{width:340px;}.JDcontent li{margin:0 0 10px 28px;}<\/style>");
document.writeln("<\/head>");
document.writeln("<body>");
document.writeln("    <ul class=\"clearfix JDimgList\">");
document.writeln("        		<li><a title=\"那些欲罢不能的女孩\" href=\"http:\/\/www.km18.net\/\">");
document.writeln("				<img alt=\"那些欲罢不能的女孩\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z20140209204555.jpg\" height=\"90\" width=\"120\"><p>那些欲罢不能的女孩<\/p><\/a>");
document.writeln("		<\/li>");
document.writeln("				<li><a title=\"iOS8已定稿多图曝光\" href=\"http:\/\/kansha.bkjia.com\/kansha\/45.html?1391939816\">");
document.writeln("				<img alt=\"iOS8已定稿多图曝光\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z1_1391754888_0207.jpg\" height=\"90\" width=\"120\"><p>iOS8已定稿多图曝光<\/p><\/a>");
document.writeln("		<\/li>");
document.writeln("				<li><a title=\"最新iPhone 6震撼谍照\" href=\"http:\/\/kansha.bkjia.com\/kansha\/47.html\">");
document.writeln("				<img alt=\"最新iPhone 6震撼谍照\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z6_1391759615_0207.jpg\" height=\"90\" width=\"120\"><p>最新iPhone 6震撼谍照<\/p><\/a>");
document.writeln("		<\/li>");
document.writeln("				<li><a title=\"衣服快撑破了呼之欲出\" href=\"http:\/\/kansha.bkjia.com\/other\/26.html?1391941012\">");
document.writeln("				<img alt=\"衣服快撑破了呼之欲出\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z16644.jpg\" height=\"90\" width=\"120\">");
document.writeln("				<p>衣服快撑破了呼之欲出<\/p><\/a>");
document.writeln("		<\/li>");
document.writeln("		<li><a title=\"性感让人尖叫女程序员\" href=\"http:\/\/kansha.bkjia.com\/kansha\/23.html\">");
document.writeln("			<img alt=\"性感让人尖叫女程序员\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z11111.jpg\" height=\"90\" width=\"120\"><p>性感让人尖叫女程序员<\/p><\/a>");
document.writeln("		<\/li>");
document.writeln("				<li><a title=\"让你口水的娇嫩模特\" href=\"http:\/\/kansha.bkjia.com\/other\/30.html?1391938694\">");
document.writeln("				<img alt=\"让你口水的娇嫩模特\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z201444.jpg\" height=\"90\" width=\"120\"><p>让你口水的娇嫩模特<\/p><\/a>");
document.writeln("		<\/li>");
document.writeln("		<li><a title=\"90后童颜巨乳Barbie可儿\" href=\"http:\/\/kansha.bkjia.com\/other\/69.html?1391941162\">");
document.writeln("				<img alt=\"90后童颜巨乳Barbie\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z20140209182006.jpg\" height=\"90\" width=\"120\"><p>90后童颜巨乳Barbie<\/p><\/a>");
document.writeln("		<\/li>");
document.writeln("		<li><a title=\"性感美女比基尼诱惑写真\" href=\"http:\/\/kansha.bkjia.com\/other\/68.html?1391941168\">");
document.writeln("				<img alt=\"性感美女比基尼诱惑写真\" src=\"http:\/\/js.bkjia.com\/bkjia\/jsimages\/z20140209182250.jpg\" height=\"90\" width=\"120\"><p>性感美女比基尼诱惑写真<\/p><\/a>");
document.writeln("		<\/li><\/ul>");
document.writeln("<\/body><\/html>")