
jQuery.extend(jQuery.easing,{easeOutBounce:function(f,g,a,j,h){if((g/=h)<(1/2.75)){return j*(7.5625*g*g)+a}else{if(g<(2/2.75)){return j*(7.5625*(g-=(1.5/2.75))*g+0.75)+a}else{if(g<(2.5/2.75)){return j*(7.5625*(g-=(2.25/2.75))*g+0.9375)+a}else{return j*(7.5625*(g-=(2.625/2.75))*g+0.984375)+a}}}}});(function(a){a.fn.wtrendMsg=function(h){var m={proId:"p281723",follows:[],checkTimer:60000,callback:function(){}};var s=a.extend({apiGetFollowData:"http://detail.zol.com.cn/xhr_Header_WTrendEnter_",apiDoFollow:"http://detail.zol.com.cn/xhr_WTrend_AttendPro_",wtrendStrollPage:"http://detail.zol.com.cn/dongtai/stroll",wtrendFollowPage:"http://detail.zol.com.cn/dongtai/home",wtrendVisitedPage:"http://detail.zol.com.cn/dongtai/home?range=visit"},m,h);var o=a(this);window.WtrendCallback={};var j=get_cookie("zol_userid");var b=false;var n=false;var g="msg";var l=false;var u=function(v){var w=o.parent().find("[data-tips="+v+"]");a(window).scroll(function(){if(l){return}
var x=a(window).scrollTop();if(x>300&&w.length!=0){w.fadeIn();if(v=="follow"){a("#callFollow").removeClass("call-follow").addClass("close-follow").attr("flag","1")}}
if(x<=300){w.fadeOut();if(v=="follow"){a("#callFollow").removeClass("close-follow").addClass("call-follow").removeAttr("flag")}}})};var q=function(v){if(v==1&&a("#wtrendFollowMsg").length!=0&&!a("#wtrendFollowMsg").has("i").length){a("#wtrendFollowMsg").append("<i></i>")}
if(v==2&&a("#wtrendVisitedMsg").length!=0&&!a("#wtrendVisitedMsg").has("i").length){a("#wtrendVisitedMsg").append("<i></i>")}};var f=function(v){if(a("#wtrendFollowMsg").length!=0){a("#wtrendFollowMsg").html('<a href="'+s.wtrendFollowPage+'">\u5173\u6ce8(<em>'+v.followNum+"</em>\u6b3e)</a>")}
if(a("#wtrendVisitedMsg").length!=0){a("#wtrendVisitedMsg").html('<a href="'+s.wtrendVisitedPage+'">\u6d4f\u89c8(<em>'+v.visitedNum+"</em>\u6b3e)</a>")}};var d=function(A,x){var w=a('<div id="followAnimateImage"><div><img src="'+A+'"></div></div>');var v=a(window).scrollTop()-60;var z=o.offset().left;var y=o.offset().top;if(x){w.css({"top":v}).appendTo(a("body")).animate({"top":v+300},800,"easeOutBounce").delay(400).animate({"left":z-59,"top":y},400).delay(400).animate({"left":z,"opacity":0},400,function(){a(this).remove();if((a("#callFollow").attr("flag")=="1")&&n){a("#callFollow").click()}
l=true})}else{w.css({"left":z-59,"top":y,"margin":0}).appendTo(a("body")).delay(800).animate({"left":z,"opacity":0},600,function(){a(this).remove();if((a("#callFollow").attr("flag")=="1")&&n){a("#callFollow").click()}
l=true})}};var k=function(y){if(s.proId==""){return}
var w="follow-"+s.proId;b=y[w]["follow"]?false:true;var x=y[w]["follow"]?' data-tips="follow"':"";var v='<span id="callFollow" class="call-follow" title="\u52a0\u5173\u6ce8"></span>'+'<div class="widget-follow-layer"'+x+">"+'<div class="widget-follow-name" node-type="wtrend-follow-name-'+s.proId+'">'+y[w]["name"]+"</div>"+'<div class="widget-follow-button" node-type="wtrend-follow-button-'+s.proId+'">'+y[w]["button"]+"</div>"+"</div>";o.before(a(v));a("#callFollow").click(function(){var B=a(this);var z=B.attr("flag");var A=B.parent().find(".widget-follow-layer");if(z==1){A.fadeOut(function(){B.removeClass("close-follow").addClass("call-follow").removeAttr("flag");l=true})}else{B.addClass("close-follow").attr("flag","1");A.fadeIn()}})};var c=function(){var w=new Image();var v=+new Date();w.src="http://pvtest.zol.com.cn/images/pvevents.gif?t="+v+"&event="+"Article_follow&ip_ck="+get_cookie("ip_ck")+"&url="+document.URL};var r=function(x){var w=a("[node-type^=wtrend-follow-button]");if(w.length!=0){a.each(w,function(){var z=a(this).attr("node-type").split("-").pop();var y="follow-"+z;a(this).html(x[y]["button"])});a(".followed-button").hover(function(){a(this).addClass("followed-button-hover")},function(){a(this).removeClass("followed-button-hover")})}
var v="[action-type=wtrend_follow_button]";if(!j){a(v).zLogin();return}
a(document).on("click",v,function(E){E.preventDefault();var C=a(this);var B=C.attr("data-img");var F=C.attr("data-id");var z=a("[node-type=wtrend-follow-button-"+F+"]").find("a");var y=parseInt(C.attr("flag"));var D=C.attr("action-data").split("&");D.push("opFlag="+y,"callback=WtrendCallback.DoFollow");var A=s.apiDoFollow+D.slice(1).join("^")+".html";WtrendCallback.DoFollow=function(I){if(I){if(y==1){z.text("\u53d6\u6d88\u5173\u6ce8").attr({"class":"followed-button","flag":"0"});var H=C.parent().parent();if(H.hasClass("widget-follow-layer")){H.attr("id","");d(B,false)}else{d(B,true)}
if(F==s.proId){n=true}
b=true;var G=a(".followed-button");G.hover(function(){a(this).addClass("followed-button-hover")},function(){a(this).removeClass("followed-button-hover")})}else{z.text("\u5173\u6ce8").attr({"class":"follow-button","flag":"1"})}}
WtrendCallback.DoFollow=null};a.getScript(A,function(){c()})})};var t=function(v){if(v.msg!=""&&v.msgStatus!=0){o.find("#callWtrendMsg").addClass("new-msg").attr("title","\u6709\u65b0\u6d88\u606f\u4e86");o.find("#wtrendMsg").attr("data-tips","msg").html('<span id="closeWtrendTips"></span>'+v.msg);a("#closeWtrendTips").click(function(){if(!b){a("#callFollow").click()}
a(this).parent().fadeOut();l=true});a("[action-type=last_visited], #callWtrendMsg").click(function(){a("#closeWtrendTips").click();o.find("#callWtrendMsg").removeClass("new-msg");var w=+new Date();a.cookie("wtrend-last-visited",w,{domain:".zol.com.cn","expires":3600*24*365})})}
if(v.msgStatus==1){q(v.msgStatus)}
if(v.msgStatus==2){q(v.msgStatus)}};var p=function(w){if(!w.followNum&&!w.visitedNum){g="follow"}else{if(w.msgStatus==0){var v="follow-"+s.proId;if(s.proId!=""&&w[v]["follow"]){g="follow"}}}
u(g)};return this.each(function(){var A='<div id="wtrendMsg"></div>';o.append(a(A));var z=o.find("#wtrendMsg");o.hover(function(){if(z.html()!=""){o.find("#wtrendMsg").fadeIn()}},function(){o.find("#wtrendMsg").fadeOut()});a("#closeWtrendTips").click(function(){a(this).parent().fadeOut()});var y;if(s.follows.length==0){y=s.proId}else{y=(s.proId=="")?s.follows.join("-"):s.proId+"-"+s.follows.join("-")}
var x=j?"^userId="+j:"";var w=s.apiGetFollowData+"proIds="+y+x+"^callback=WtrendCallback.GetFollow.html";WtrendCallback.GetFollow=function(B){k(B);r(B);f(B);t(B);p(B);s.callback();WtrendCallback.GetFollow=null};a.getScript(w);if(j){var v=s.apiGetFollowData+"proIds="+y+"^userId="+j+"^callback=WtrendCallback.MsgCheck.html";WtrendCallback.MsgCheck=function(B){f(B);t(B);p(B)};a.getScript(v)}})}})(jQuery);if(temp_doc_hardware_id&&temp_doc_hardware_id!="0"&&temp_doc_hardware_id!=""){var mainFollow='<span node-type="wtrend-follow-button-p'+temp_doc_hardware_id+'" id="wtrendFollowButton"></span>';$(".nav_con .nav_title").append(mainFollow)}
$('<div id="wtrendMsgBox"><div id="callWtrend"><a id="callWtrendMsg" href="http://detail.zol.com.cn/dongtai/home" target="_blank"><i></i></a></div></div>').insertBefore(".commentbox");if(temp_doc_hardware_id&&temp_doc_hardware_id!="0"&&temp_doc_hardware_id!=""){setTimeout(function(){if(typeof(_dwrecordHistory)=="function"){_dwrecordHistory(temp_doc_sub_id,temp_doc_manu_id,temp_doc_hardware_id)}},5000)}
$(document).ready(function(){var d="\u8bf7\u8f93\u5165\u5173\u952e\u8bcd";$(".text_1").val(d);$(".text_1").click(function(){if(d==$(this).val()){$(this).val("")}
$(this).css("color","#333")});if($("#doc_tag_content").length&&0==$("#doc_tag_content").children().length){$("#doc_tag_content").hide()}
$(".close").click(function(){$(this).parent().hide();if($(this).parent().attr("class")=="ts_fy"){setCookie("doc_page_tip","1")}});$(".switch").lazyNavi("","now",200,1);$(".autoSwitch").autoNavi("","now",5000,1);$(".rank_ul>li").mouseover(function(){$(this).siblings().removeClass("cur");$(this).addClass("cur")});if($("#productRank_2 li").length<1){$("#samePriceLi").remove()}
if($(".configuration").length>0){$("#xweibo").hide();$(intel_show).show()}
function f(){var g=document.documentElement.scrollTop+document.body.scrollTop+350;if(g<b&&g>a){$("#group_pic_tip").css("visibility","visible")}else{$("#group_pic_tip").css("visibility","hidden")}}
if(document.getElementById("group_pic_tip")&&document.getElementById("group_pic_tip").length){var a=parseInt(document.getElementById("cotent_idd").getBoundingClientRect().top);var b=a+parseInt($("#cotent_idd").height());if(window.attachEvent){window.attachEvent("onscroll",f);window.attachEvent("onresize",f)}else{if(window.addEventListener){window.addEventListener("scroll",f,false);window.addEventListener("resize",f,false)}}}
var c="http://"+location.hostname+location.pathname;$("#cotent_idd").children(":last").after('<p class="hidden">\u539f\u6587\u5730\u5740:<a href="'+c+'">'+c+"</a></p>&nbsp;")});if("undefined"==typeof(temp_doc_hardware_id)){var temp_doc_hardware_id=0}
if("undefined"==typeof(temp_doc_class_id)){var temp_doc_class_id=0}
if($("#ProductInfoInner").length){var createProInfoTm=$("#ProductInfoInner").attr("rel");createProInfoTm=createProInfoTm?createProInfoTm:0;var nowTm=Date.parse(new Date());nowTm=nowTm/1000;if(nowTm-createProInfoTm>86400){ajaxCreateProInfo()}}else{ajaxCreateProInfo()}
function ajaxCreateProInfo(){if(!temp_doc_hardware_id||temp_doc_hardware_id==0){$("#ProductInfo").remove();return""}
$.ajax({type:"GET",url:"/include/showProRelArt.php",data:"pid="+temp_doc_hardware_id+"&cid="+temp_doc_class_id,success:function(a){if(temp_doc_class_id!="96"){$("#ProductInfo").html(a)}}})}
function in_array(b,a){for(i=0;i<b.length;i++){if(b[i]==a){return true}}
return false}
function update_doc_vote(c,b,d){if($("#doc_vote_good").length&&$("#doc_vote_bad").length){var a="http://dynamic.zol.com.cn/channel/vote11.php?f="+d+"&type="+b+"&c="+c;replace_js_src("doc_vote",a)}}
function new_doc_vote(c){if(c[0]){$("#doc_vote_good").html(c[0]).addClass("good")}
if(c[1]){$("#doc_vote_bad").html(c[1]).addClass("good")}
if(c[2]){$("#doc_vote_t5").html(c[2]).addClass("good")}
if(c[3]){$("#doc_vote_t6").html(c[3]).addClass("good")}
if(c[4]){$("#doc_vote_t7").html(c[4]).addClass("good")}
var b=c[0]+c[1]+c[2]+c[3]+c[4];var d=c[1]*1+c[4]*2+c[2]*3+c[0]*4+c[3]*5;var a=(d/b).toFixed(1);if(b){$("#doc_vote_total").html(b).addClass("good");$("#doc_vote_average").html(a)}}
function replace_js_src(c,b){if(1==$("#"+c).length){$("#"+c).remove()}
var a=document.createElement("script");a.src=b;a.id=c;a.charset="utf-8";document.getElementsByTagName("body")[0].appendChild(a)}
if(temp_doc_hardware_id){var pic_class="temp_pro_pic_"+temp_doc_hardware_id;$("."+pic_class+" img:eq(0)").each(function(){var b=this.offsetWidth;if(b>400){var a=$(this);if("A"==$(this).parent().attr("tagName")){a=$(this).parent()}
if("BR"==a.next().attr("tagName")){a.next().remove()}
a.wrap('<span style="width:'+b+'px;" class="pro_pic_rel"></span>');a.after('<span style="width:'+(parseInt(b))+'px;" class="pro_pic_abs_back"></span><span style="width:'+(parseInt(b)-10)+'px;" class="pro_pic_abs"><a class="pro_pic_abs_close" onclick="close_pro_pic_abs()">\u5173\u95ed<img src="http://icon.zol-img.com.cn/article/2011/close.jpg" width="18" height="19" alt="\u5173\u95ed"/></a>'+temp_doc_hardware_info+"</span>")}});function show_pro_detail(data){var special_flag=1;if(2==temp_doc_sub_id||3==temp_doc_sub_id){special_flag=0}
if(data.picNum&&special_flag){$(".temp_pro_picNum").html("\u56fe\u7247("+(data.picNum-0)+")")}
if(data.commNum&&special_flag){$(".temp_pro_commNum").html("\u70b9\u8bc4("+(data.commNum-0)+")")}
if(data.bbsNum&&special_flag){$(".temp_pro_bbsNum_1").html("\u8bba\u575b("+(data.bbsNum-0)+")")}
if(data.SeriesProNum&&special_flag){$(".temp_pro_seriesNum").html("\u7cfb\u5217(\u5171"+(data.SeriesProNum-0)+"\u6b3e)")}
if(data.userGrade){$(".temp_pro_userGrade").html(data.userGrade-0)}else{$(".temp_pro_userGrade").parent().hide()}
if(data.zolGrade){$(".temp_pro_zolGrade").html(data.zolGrade-0)}else{$(".temp_pro_zolGrade").parent().hide()}
if(data.price-0==0||data.price-0==0){$(".temp_pro_price").parent().hide()}else{if((data.price-0+"").length>4){$(".temp_pro_price").html("\uffe5"+data.price)}else{$(".temp_pro_price").html("\uffe5"+data.price)}}
var merchant=data.merchantInfo;var mer_str="";if(merchant+""){var mer_i=1;var mer_class="";for(var i in merchant){var mer=merchant[i];var re=new RegExp(/[\d-]+/);var tele="";if(mer.tel){tele=mer.tel.match(re);if((tele+"").length<5){tele=mer.tel.match(/[\d]+ [\d]+/)}
if(tele){tele=String(tele);tele=tele.replace(" ","-");tele='<span class="tele">'+tele+"</span>"}}
if(!tele){tele='<span class="notele">\u3000</span>'}
if(0==mer_i%2){mer_class=' class="odd"'}else{mer_class=""}
if(1==mer_i){mer_class=' class="act"'}
mer_str+="<li"+mer_class+'><em class="clearfix"><a href="'+mer.url+'" class="a_1">'+mer.name+"</a>"+tele+' <a href="'+mer.url+'">\u8be6\u7ec6>></a></em> <em class="clearfix li_2"> <em class="tu_p">'+mer.credit+'</em> <a href="'+mer.commUrl+'" class="pja">\u7528\u6237\u8bc4\u4ef7\uff08<b class="red">'+(mer.merComm-0)+"</b>\u6761)</a></em> </li>";mer_i++}
$(".temp_pro_merchant").html(mer_str);$(".temp_pro_merchant_show").show();$(".temp_pro_merchant li").mouseover(function(){$(this).siblings().removeClass("act");$(this).addClass("act")})}else{$(".temp_pro_merchant_show").remove();removeTopFirstMargin()}
if(1==$(".param_table").length&&data.paramLink){$(".param_value").each(function(){var id=$(this).attr("id");eval("var value = data.paramLink."+id+";");$(this).html(value)})}}
if(96==temp_doc_class_id||311==temp_doc_class_id||302==temp_doc_class_id){var province_id="undefined"==typeof(temp_doc_province_id)?0:parseInt(temp_doc_province_id);var city_id="undefined"==typeof(temp_doc_city_id)?0:parseInt(temp_doc_city_id)}else{var show_ip_arr=[30,10,17,22,23,21,3,4,20,6];var province_id="undefined"==typeof(adProvinceId)?0:parseInt(adProvinceId);var city_id="undefined"==typeof(adCityId)?0:parseInt(adCityId);if(!(province_id>1&&in_array(show_ip_arr,province_id))){province_id=0;city_id=0}}
var target="http://detail.zol.com.cn/corp_zol_proId="+temp_doc_hardware_id+"^provinceId="+province_id+"^cityId="+city_id+"^merLen=18^merCnt=5^jsonCallBack=show_pro_detail.html?v=2";replace_js_src("pro_detail_js",target);removeTopFirstMargin();var dealer_info_ids_arr=[];if(1==$("#info_more").length){function show_pro_look_more(b){if(b&&b.length>5){var h='<div class="dealer_info"><div class="dealer_tit clearfix"><strong>\u770b\u4e86\u8be5\u4ea7\u54c1\u7684\u7528\u6237\u8fd8\u559c\u6b22</strong></div><ul class="dealer_piclist clearfix">';var g='<dl class="li_connot"><dt>\u770b\u8fc7 <span>\u8be5\u4ea7\u54c1</span> \u7684\u4eba\u8fd8\u5173\u6ce8</dt><dd><ul>';var c=b.length;for(var j in b){var k=b[j];var d="";if(parseInt(j)+1==c){d=' class="last"'}
if("undefined"!=typeof(k.url)){var f=/index([0-9]+).shtml/;var a=f.exec(k.url);dealer_info_ids_arr[j]="p"+a[1];h+="<li"+d+'><a href="'+k.url+'" title="'+k.name+'"><img src="'+k.pic+'" width="80" height="60">'+k.name+'</a><p node-type="wtrend-follow-button-p'+a[1]+'"></p></li>'}}
h+="</ul></div>";$(".product_info").after(h)}}
function show_pro_detail_down(d){var h="";h+='<div class="product_info clearfix"><div class="product_img"><a href="'+d.defaultUrl+'"><img src="'+d.proPicUrl+'" width="120" height="90" alt=""></a><span></span><a class="img_num" href="'+d.picUrl+'">\u56fe\u7247\uff08'+(d.proPicNum-0)+'\uff09</a></div><dl><dt><span class="more"><a href="'+d.subManuUrl+'">'+d.subManuName+'</a> | <a href="'+d.subcateurl+'">\u66f4\u591a'+d.subcateName+'\u62a5\u4ef7>></a></span> <strong><a href="'+d.defaultUrl+'">'+d.proName+"</a></strong></dt>";var b=4;if(d.seriesName&&d.seriesUrl){h+='<dd>\u6240\u5c5e\uff1a<a href="'+d.seriesUrl+'">'+d.seriesName+"</a></dd>";b=3}
if(d.baseParam){for(var c=0;c<b;c++){if(d.baseParam[c]){h+="<dd>"+d.baseParam[c].paramMainName+"\uff1a"+d.baseParam[c].paramMainValue+"</dd>"}}}
var f=parseInt(d.userGrade*11);h+='<dd class="score">\u7f51\u53cb\u8bc4\u5206\uff1a <span class="xbg2"><em style="width: '+f+'px;" class="xbg3"></em></span>'+d.userGrade+'\u5206<span>&nbsp;&nbsp;<a href="'+d.reviewUrl+'">\u70b9\u8bc4('+(d.reviewNum-0)+')</a> | <a href="'+d.defaultUrl+'">\u4ea7\u54c1</a> | <a href="'+d.paramUrl+'">\u53c2\u6570</a> | <a href="'+d.priceUrl+'">\u62a5\u4ef7</a> | <a href="'+d.articleUrl+'">\u884c\u60c5&middot;\u8bc4\u6d4b</a> | <a href="'+d.bbsUrl+'">\u5e16\u5b50('+(d.bbsNum-0)+")</a></span></dd></dl></div>";if(d.merchantInfo&&d.merchantInfo[1]){var g=d.merchantInfo[1].merchantInfo;if(g){h+='<div class="dealer_info"><div class="dealer_tit clearfix"><a class="more" href="'+d.priceUrl+'">\u66f4\u591a&gt;&gt;</a><strong>\u7ecf\u9500\u5546</strong></div><ul class="dealer_list clearfix">';var c=1;for(var l in g){var m=new RegExp(/[\d-]+/);var k="";var j="";if(g[l].telephone){k=g[l].telephone.match(m);if((k+"").length<5){k=g[l].telephone.match(/[\d]+ [\d]+/)}}
if(g[l].creditStar){j=g[l].creditStar}
h+='<li><a href="'+g[l].url+'">'+g[l].name+'</a><div class="star">'+j+'</div><div class="tel">'+k+"</div></li>";if(6==c){break}
c++}
h+="</ul>"}}
$("#info_more").html(h).show();var a="http://detail.zol.com.cn/Api_Article_LookMore_proId="+temp_doc_hardware_id+"%5Ecallback=show_pro_look_more.html";replace_js_src("pro_detail_look_more",a)}
if(96==temp_doc_class_id||311==temp_doc_class_id||302==temp_doc_class_id){var province_id="undefined"==typeof(temp_doc_province_id)?0:parseInt(temp_doc_province_id);var city_id="undefined"==typeof(temp_doc_city_id)?0:parseInt(temp_doc_city_id)}else{var show_ip_arr=[23,30,10,17,11];var province_id="undefined"==typeof(adProvinceId)?0:parseInt(adProvinceId);var city_id="undefined"==typeof(adCityId)?0:parseInt(adCityId);if(!(province_id>1&&in_array(show_ip_arr,province_id))){province_id=0;city_id=0}}
var target="http://detail.zol.com.cn/Corp_ArtMerchantRecommend_proId="+temp_doc_hardware_id+"^provinceId="+province_id+"^cityId="+city_id+"^jsonCallBack=show_pro_detail_down.html?v=2";replace_js_src("pro_detail_js_down",target)}}else{$(".temp_pro_merchant_show").remove()}
if(0==temp_doc_hardware_id){$("#ProductInfo").remove()}
if($("#rightAdDiv1").html()==""||$("#rightAdDiv1").children().length==0){$("#rightAdDiv1").remove()}
if($("#rightAdDiv2").html()==""||$("#rightAdDiv2").children().length==0){$("#rightAdDiv2").remove()}
if($("#rightAdDiv3").html()==""||$("#rightAdDiv3").children().length==0){$("#rightAdDiv3").remove()}
if($("#rightAdDiv4").html()==""||$("#rightAdDiv4").children().length==0){$("#rightAdDiv4").remove()}
if($("#commentTopAd").html()==""||$("#commentTopAd").children().length==0){$("#commentTopAd").remove()}
try{eval("new_article_right_ad")}catch(e){$("#rightAdDiv1").remove()}
try{eval("new_article_right_ad3")}catch(e){$("#rightAdDiv3").remove()}
function removeTopFirstMargin(){$("#main_right > div:first-child").css("margin-top","0")}
removeTopFirstMargin();function close_pro_pic_abs(){$(".pro_pic_abs_back").remove();$(".pro_pic_abs").remove()}
function new_doc_vote_tip(a){if(0==$("#doc_tip").length){obj=document.createElement("div");obj.id="doc_tip";document.getElementsByTagName("body")[0].appendChild(obj)}
$("#doc_tip").html(a).windowCenter(0,0);setTimeout(function(){$("#doc_tip").animate({opacity:0},1000)},2000)}(function(a){a.fn.windowCenter=function(b,j){var c=a(window).height()-this.height();var g=(c)/2;var f=(a(window).width()-this.width())/2;var d=a(document).scrollTop();var h=a(document).scrollLeft();this.css({top:c+d+j,"left":f+h+b,"opacity":0.2}).show();this.animate({top:g+d+j,opacity:1},500)}})(jQuery);$(".sense li a").hover(function(){$(this).addClass("focus_red");$(this).siblings().addClass("focus_red")},function(){$(this).removeClass("focus_red");$(this).siblings().removeClass("focus_red")});try{var temp_doc_root_id="undefined"!=typeof(temp_doc_root_id)?temp_doc_root_id:temp_doc_doc_id;var show_intel_arr=[210,332,300,74,62,182,336,228,231];if(in_array(show_intel_arr,temp_doc_class_id)){var show_intel_active_arr=[300,74,210];if(in_array(show_intel_active_arr,temp_doc_class_id)){var portalInfo=[{imgSrc:"http://icon.zol-img.com.cn/article/201308/article_nb_active.png?130816",imgWidth:55,imgHeight:70,contentSrc:"http://nb.zol.com.cn/topic/3913679.html",contentWidth:300,contentHeight:230,adClick:"http://ad-apac.doubleclick.net/click;h=v2|411C|0|0|*|t;275353561;0-0;0;102278382;31-1|1;53582496|53499555|1;;?http://ad-apac.doubleclick.net/dot.gif"}]}
if(62==temp_doc_class_id||182==temp_doc_class_id||336==temp_doc_class_id){var portalInfo=[{imgSrc:"http://icon.zol-img.com.cn/article/201308/article_nb_active.png?130816",imgWidth:55,imgHeight:70,contentSrc:"http://cpu.zol.com.cn/topic/3939232.html",contentWidth:300,contentHeight:230,adClick:"http://ad-apac.doubleclick.net/click;h=v2|4126|0|0|*|z;275647840;0-0;0;102675399;31-1|1;53582496|53499555|1;;?http://ad-apac.doubleclick.net/dot.gif"}]}
if(332==temp_doc_class_id||228==temp_doc_class_id||231==temp_doc_class_id){var portalInfo=[{imgSrc:"http://icon.zol-img.com.cn/article/201308/article_nb_active.png?130816",imgWidth:55,imgHeight:70,contentSrc:"http://ultrabook.zol.com.cn/topic/3939592.html",contentWidth:300,contentHeight:230,adClick:"http://ad-apac.doubleclick.net/click;h=v2|4126|0|0|*|z;275647830;0-0;0;102675383;31-1|1;53582496|53499555|1;;?http://ad-apac.doubleclick.net/dot.gif"}]}
var target="http://icon.zol-img.com.cn/article/js/zever_assist_script.js?platform=zol&articleID="+temp_doc_root_id+"&cate_id="+temp_doc_class_id+"&width=980&ztime="+Math.ceil(Date.parse(new Date())/10000);replace_js_src("zever_assist",target);var loadIntelAnaloop=0;function loadIntelAna(){loadIntelAnaloop++;if(loadIntelAnaloop>10){return false}
if($("#cms_art_intel").size()==0){setTimeout(function(){loadIntelAna()},1000);return false}
var a=[{type:"click",id:"cms_art_intel",rate:1}];moduleHeat.init(a)}
setTimeout(function(){loadIntelAna()},1000)}}catch(e){}
if($("#bdshare").length&&"undefined"!=typeof(temp_doc_root_url)){$("#bdshare").attr("data",'{"url":"'+temp_doc_root_url+'"}')}
if(typeof($.fn.Motu)!="undefined"){$("#cotent_idd img").Motu({type:"share"})}
if(typeof(temp_doc_root_id)!="undefined"){var moduleHeatConfig=[{type:"click",id:"related_reading_1",param:"&cid"+temp_doc_class_id+"&rid"+temp_doc_root_id+"&did"+temp_doc_doc_id+"&sid"+temp_doc_sub_id+"&mid"+temp_doc_manu_id+"&pid"+temp_doc_hardware_id,condition:function(){return true},rate:1},{type:"click",id:"related_reading_2",param:"&cid"+temp_doc_class_id+"&rid"+temp_doc_root_id+"&did"+temp_doc_doc_id+"&sid"+temp_doc_sub_id+"&mid"+temp_doc_manu_id+"&pid"+temp_doc_hardware_id,condition:function(){return true},rate:1},{type:"click",id:"mylike_list",param:"&cid"+temp_doc_class_id+"&rid"+temp_doc_root_id+"&did"+temp_doc_doc_id+"&sid"+temp_doc_sub_id+"&mid"+temp_doc_manu_id+"&pid"+temp_doc_hardware_id,condition:function(){return true},rate:1}]}
$(".switc").lazyNavi("","cur",200,1);$(".extra").click(function(){random_num=$(".circle-dot span").index($(".circle-dot .cur"))+1;if(random_num>2){random_num=0}
$(".circle-dot span:eq("+random_num+")").mouseover();random_num++});var scroll_flag=false;var bindId=1;var has_maylike_flag=true;var fix_show_flag=false;var ie6_flag=false;var view_height=parseInt(document.documentElement.clientHeight);var fix_bar_height=158;var content_pos=parseInt($("#cotent_idd").offset().top);var content_height=parseInt($("#cotent_idd").height());if(!fix_show_flag){$(".fixed-share-bar").css({"position":"absolute","top":content_pos}).show();fix_show_flag=true}
if(typeof(temp_doc_page_num)=="undefined"||typeof(temp_doc_page_index)=="undefined"||temp_doc_page_index!=temp_doc_page_num||in_array(show_intel_arr,temp_doc_class_id)){$(".may-like").hide();$(".like").hide();has_maylike_flag=false}
if($.browser.msie&&($.browser.version==6)){ie6_flag=true}
$(window).bind("scroll",function(d){var c=$(window).scrollTop();var b=0;var a=content_height;if(1==$("#commentsiframe").length){b=parseInt($("#commentsiframe").css("height"));a=parseInt($("#commentsiframe").offset().top)}
if(has_maylike_flag){if(!scroll_flag&&c>a+b+100-view_height){$(".may-like").show();scroll_flag=true}
if(c<a+b+100-view_height){$(".may-like").hide()}}
if(c>content_pos-200){if(c>a+b-200){$(".fixed-share-bar").css({"position":"absolute","top":a+b-fix_bar_height})}else{if(ie6_flag){$(".fixed-share-bar").css({"top":c+200})}else{$(".fixed-share-bar").css({"position":"fixed","bottom":"auto","top":"200px"})}}}else{$(".fixed-share-bar").css({"position":"absolute","top":content_pos})}
if(c>1000){$(".commentbox").show()}else{$(".commentbox").hide()}});$(".like").live("click",function(){$(".may-like").show()});var new_val="\u8bf7\u8f93\u5165\u8981\u67e5\u8be2\u7684\u4ea7\u54c1";$(".skey").val(new_val);$(".skey").click(function(){if(new_val==$(this).val()){$(this).val("")}
$(this).css("color","#333")});if($("#related_reading_2").length>0&&$("#related_reading_2").children().length==0){try{var target="http://dynamic.zol.com.cn/channel/rel_doc_data.php?doc_id="+temp_doc_doc_id+"&class_id="+temp_doc_class_id+"&title="+encodeURIComponent(temp_doc_title);replace_js_src("rel_doc_js",target)}catch(e){}}else{$("#related_reading_2").hide()}
function rel_doc(a){if(a){$("#related_reading_2").html(a.html)}}
if(typeof(temp_doc_page_index)!="undefined"&&temp_doc_page_index==1){var up="subcateId="+temp_doc_sub_id+"&manuId="+temp_doc_manu_id+"&proId="+temp_doc_hardware_id+"&docId="+temp_doc_doc_id+"&classId="+temp_doc_class_id;var mojingCfg=[{site:"doc",type:"Doc_Detail",param:up,mustlogin:1}]}
function cutString(f,a){if(typeof(f)!="string"){return null}
if(!(/^[0-9]*[1-9][0-9]*$/).test(a)){return f}
if(a==0){return f}
var d=0,c="";for(var b=0;b<f.length;b++){if(f.charCodeAt(b)>255){d+=2}else{d++}
if(d<=a-2){c+=f.charAt(b)}else{if(b==f.length-1){c+=f.charAt(b)}else{c+=".."}
break}}
return c}
window.contentShareConf={contentId:"cotent_idd"};(function(){if(!window.contentShareConf){window.contentShareConf={}}
var sX,sY;window.contentShare={bindTextArea:function(id){var box=document.getElementById(id);if(!box){return}
addEvent(box,"mousedown",function(e){sX=e.pageX||(e.clientX+document.documentElement.scrollLeft);sY=e.pageY||(e.clientY+document.documentElement.scrollTop)});addEvent(box,"mouseup",function(e){var x=e.pageX||(e.clientX+document.documentElement.scrollLeft),y=e.pageY||(e.clientY+document.documentElement.scrollTop);if(x==sX&&y==sY){return}
var text="";if(e.button==2){return}
if(window.getSelection){text=window.getSelection().toString()}else{if(document.selection){text=document.selection.createRange().text}}
if(text==""){return}
text=text.replace(/[\r\n]/g,"");text=text.replace(/\u539f\u6587\u5730\u5740:.*html/g,"");_contentShare.text=text;showShare(x,y);if(_keywordLayer.keywordLayer){_keywordLayer.hideKeywordLayer()}})}};contentShare.bindTextArea(contentShareConf.contentId||"cotent_idd");addEvent(document.body,"mousedown",function(e){hideShare()});var shareLayerDiv,showStatus=false;function showShare(x,y){createShare();showStatus=true;shareLayerDiv.style.display="block";shareLayerDiv.style.left=x-30+"px";shareLayerDiv.style.top=y+5+"px"}
function hideShare(){if(!showStatus){return}
if(shareLayerDiv){shareLayerDiv.style.display="none"}
showStatus=false}
function createShare(){if(shareLayerDiv){return}
shareLayerDiv=document.createElement("div");document.body.insertBefore(shareLayerDiv,document.body.firstChild);shareLayerDiv.className="draglayer";shareLayerDiv.onmousedown=function(e){e=e||event;e.stopPropagation?e.stopPropagation():(e.cancelBubble=true)};var html='<i class="ico"></i><div class="draglayer-content"><div class="writing-reviews clearfix" id="writing-reviews" style="width:64px;"><a onclick="_contentShare.share(\'comment\');" href="javascript:void(0)" target="_self" title="\u8bc4\u8bba\u8fd9\u6bb5\u5185\u5bb9">\u8bc4\u8bba</a><a class="share-word" onmouseover="_contentShare.showShareDetail()" onmouseout="_contentShare.hideShareDetail()" href="javascript:void(0)" target="_self" title="\u5206\u4eab\u8fd9\u6bb5\u5185\u5bb9">\u5206\u4eab</a><div class="share" style="display:none;" id="share-detail" onmouseover="_contentShare.showShareDetail()" onmouseout="_contentShare.hideShareDetail()">';for(var i=0;i<_contentShare.btns.length;i++){html+='<a href="javascript:void(0)" onclick="_contentShare.share(\''+_contentShare.btns[i].className+'\');return false;" class="'+_contentShare.btns[i].className+'" title="\u5206\u4eab\u5230'+_contentShare.btns[i].title+'"></a>'}
html+="</div></div></div></div>";shareLayerDiv.innerHTML=html;var moduleHeatConfig3=[{type:"click",id:"share-detail",param:"url=http://"+location.hostname+location.pathname,rate:1}];moduleHeat.init(moduleHeatConfig3)}
window._contentShare={text:("undefined"==typeof(temp_doc_title)?document.title:temp_doc_title),url:("undefined"==typeof(temp_doc_root_url)?temp_doc_root_url:"http://"+location.hostname+location.pathname),pic:(document.getElementById("content-first-img")?document.getElementById("content-first-img").src:""),btns:[{title:"\u65b0\u6d6a\u5fae\u535a",className:"sina",url:"http://service.weibo.com/share/share.php?url=[$url]&title=[$text]&pic=[$pic]&appkey=4028615622&ralateUid=1747383115"},{title:"\u817e\u8baf\u5fae\u535a",className:"qweibo",url:"http://share.v.t.qq.com/index.php?c=share&a=index&url=[$url]&title=[$text]&pic=[$pic]&appkey=99d207b90670adceaaa416b63528d92c"},{title:"QQ\u7a7a\u95f4",className:"qzone",url:"http://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=[$url]&title=[$text]&pics=[$pic]&summary="}],share:function(className){hideShare();if("comment"==className){var comment_textarea=document.getElementById("commentsiframe").contentWindow.document.getElementById("content");var comment_str="#"+this.text+"#\u3000";comment_textarea.value="";insertText(comment_textarea,comment_str);comment_textarea.oninput();return}
for(var i=0;i<this.btns.length;i++){if(this.btns[i].className==className){url=this.btns[i].url;url=url.replace(/\[\$text\]/g,encodeURIComponent(cutString(this.text,200)));url=url.replace(/\[\$pic\]/g,encodeURIComponent(this.pic));url=url.replace(/\[\$url\]/g,encodeURIComponent(this.url));window.open(url,"contentShare","toolbar=0,status=0,resizable=1,width="+this.btns[i].width+",height="+this.btns[i].height+",left="+Math.round(screen.width/2-this.btns[i].width/2)+",top="+Math.round(screen.height/2-this.btns[i].height/2));break}}},showShareTimeout:"",showShareDetail:function(){clearTimeout(_contentShare.showShareTimeout);document.getElementById("share-detail").style.display="block";document.getElementById("writing-reviews").style.width="148px"},hideShareDetail:function(){_contentShare.showShareTimeout=setTimeout(function(){document.getElementById("share-detail").style.display="none";document.getElementById("writing-reviews").style.width="64px"},200)}};function addEvent(obj,eventType,func){if(obj.attachEvent){obj.attachEvent("on"+eventType,func)}else{obj.addEventListener(eventType,func,false)}}
function insertText(obj,str){obj.focus();if(document.selection){var sel=document.selection.createRange();sel.text=str}else{if(typeof obj.selectionStart=="number"&&typeof obj.selectionEnd=="number"){var startPos=obj.selectionStart,endPos=obj.selectionEnd,cursorPos=startPos,tmpStr=obj.value;obj.value=tmpStr.substring(0,startPos)+str+tmpStr.substring(endPos,tmpStr.length);cursorPos+=str.length;obj.selectionStart=obj.selectionEnd=cursorPos;window.location.hash="#add_comment";window.location=window.location}else{obj.value+=str}}}
window._keywordLayer={keywordLayer:false,keywordDocLayer:false,initKeywordLayer:function(){if(_keywordLayer.keywordLayer){return}
var keywordLayer=document.createElement("div");keywordLayer.style.display="none";document.body.insertBefore(keywordLayer,document.body.firstChild);keywordLayer.className="draglayer";keywordLayer.innerHTML='<i class="ico"></i><i class="closed" onclick="_keywordLayer.hideKeywordLayer()"></i>';var keywordDocLayer=document.createElement("div");keywordDocLayer.className="draglayer-content";keywordDocLayer.id="keyword-layer";keywordLayer.appendChild(keywordDocLayer);_keywordLayer.keywordLayer=keywordLayer;_keywordLayer.keywordDocLayer=keywordDocLayer},initKeywordDocLayer:function(str,obj){_keywordLayer.initKeywordLayer();var x=parseInt(_keywordLayer.absPos(obj,"left")),y=parseInt(_keywordLayer.absPos(obj,"top"));if(x==sX&&y==sY&&_keywordLayer.keywordLayer.style.display!="none"){return}
sX=x;sY=y;_keywordLayer.keywordDocLayer.innerHTML="\u6570\u636e\u8f7d\u5165\u4e2d...";_keywordLayer.keywordLayer.style.left=x+"px";_keywordLayer.keywordLayer.style.top=y+20+"px";_keywordLayer.keywordLayer.style.display="block";var target="http://dynamic.zol.com.cn/channel/keyword_doc.php?class_id="+temp_doc_class_id+"&str="+encodeURIComponent(str)+"&doc_id="+temp_doc_root_id;replace_js_src("keyword_doc",target)},showKeywordDocLayer:function(data){if(data.length>0){var str='<ul class="news-list">';for(var i in data){str+='<li><a href="'+data[i].url+'">'+data[i].title+"</a></li>"}
str+="</ul>"}else{var str="\u6682\u65e0\u76f8\u5173\u6587\u7ae0";setTimeout(function(){_keywordLayer.hideKeywordLayer()},500)}
_keywordLayer.keywordDocLayer.innerHTML=str;var moduleHeatConfig4=[{type:"click",id:"keyword-layer",param:"url=http://"+location.hostname+location.pathname,rate:1}];moduleHeat.init(moduleHeatConfig4)},hideKeywordLayer:function(){_keywordLayer.keywordDocLayer.innerHTML="";_keywordLayer.keywordLayer.style.display="none"},absPos:function(obj,direction){var pos="";while(obj!=null){pos+=eval("obj.offset()."+direction);obj=obj.offset().parent}
return pos}};addEvent(document.body,"click",function(){if(_keywordLayer.keywordLayer){_keywordLayer.hideKeywordLayer()}});var keywordLayerTimeout="";$(".hui14_line").hover(function(){var str=$(this).html();var obj=$(this);keywordLayerTimeout=setTimeout(function(){_keywordLayer.initKeywordDocLayer(str,obj);hideShare()},300)},function(){clearTimeout(keywordLayerTimeout)})})();$("#main_right").append('<div id="focus_look" class="instant-focus mt10"><div class="instant-focus-header clearfix"><h3>\u5373\u65f6\u7126\u70b9</h3><span>\u5927\u5bb6\u6b63\u5728\u770b\u4ec0\u4e48</span><span class="focus_update" style="float:right;cursor:pointer">\u6362\u4e00\u6362</span></div><div style="text-align:center;margin-top:5px;" id="jsjd"></div><div id="focus_look_div"></div></div>');var posTop=$("#focus_look").offset().top-$("#focus_look").height()+250;var left=$("#main_left").height();var right=$("#main_right").height();function focus_look_move(){var a=$(document).scrollTop();if(left>right){if(a<posTop){$("#focus_look").removeClass("look_more_fix")}else{$("#focus_look").addClass("look_more_fix")}}}
var flag=0;var freshObj;var freshObj=$(".focus_update");var focusLookUrl="http://dynamic.zol.com.cn/channel/moment.php?cid="+temp_doc_class_id+"&did="+temp_doc_doc_id+"&uid=";var focusUid="";if(typeof(readck)!="undefined"){focusUid=readck("zol_userid");if(!focusUid){focusUid=readck("last_userid")}}else{if(typeof(get_cookie)!="undefined"){focusUid=get_cookie("zol_userid");if(!focusUid){focusUid=get_cookie("last_userid")}}}
focusLookUrl+=focusUid;$(".focus_update").click(function(){var b=0;var a=$("#focus_look_div ul").length-1;if(bindId>a){bindId=0}
$("#focus_look_div ul:eq("+bindId+")").show();$("#focus_look_div ul").not(":eq("+bindId+")").hide();bindId=bindId+1});if(document.getElementById("focus_look")){if(window.attachEvent){window.attachEvent("onscroll",focus_look_move);window.attachEvent("onresize",focus_look_move)}else{if(window.addEventListener){window.addEventListener("scroll",focus_look_move,false);window.addEventListener("resize",focus_look_move,false)}}}
if($("#focus_look")){var target=focusLookUrl+"&callback=focus_look_fun";replace_js_src("doc_focus_look",target)}
var JSONP={removeElem:function(b){var a=b.parentNode;if(a&&a.nodeType!==11){a.removeChild(b)}},rand:function(){return Math.random().toString().substr(2,1)},parseData:function(c){var a="";if(typeof c==="string"){a=c}else{if(typeof c==="object"){for(var b in c){a+="&"+b+"="+encodeURIComponent(c[b])}}}
a=a.substr(1);return a},getJSON:function(c,h,g){var b;c=c+(c.indexOf("?")===-1?"?":"&")+"t="+this.rand()+"&"+this.parseData(h);var a=/callback=(\w+)/.exec(c);if(a&&a[1]){b=a[1]}else{b="jsonpCallback";c=c.replace("callback=?","callback="+b);c=c.replace("callback=%3F","callback="+b)}
var f=document.createElement("script");f.type="text/javascript";f.src=c;f.id="id_"+b;window[b]=function(j){window[b]=undefined;var k=document.getElementById("id_"+b);JSONP.removeElem(k);g(j)};var d=document.getElementsByTagName("head");if(d&&d[0]){d[0].appendChild(f)}}};function focus_look_fun(f){var d=Date.parse(new Date())/1000;var h="";if(f){var k="";var a=1;k+='<ul id="tab-x-1" class="instant-focus-list">';for(var c=0;c<6;c++){if("undefined"==typeof(f[c])){break}
if(temp_doc_doc_id==f[c]["did"]){continue}
h="";var g=d-f[c]["tm"];if(Math.floor(g/60)<60){h=Math.floor(g/60)+"\u5206\u949f\u524d";if(Math.floor(g/60)<1){h="1\u5206\u949f\u524d"}}else{if(Math.floor(g/3600)<24){h=Math.floor(g/3600)+"\u5c0f\u65f6\u524d"}else{h=Math.floor(g/86400)+"\u5929\u524d"}}
k+="<li data-tm="+h+'><a href="'+f[c]["url"]+'" class="pic"><img width="100" height="75" src="'+f[c]["img"]+'" alt="'+f[c]["title"]+'"></a><h3><a href="'+f[c]["url"]+'">'+f[c]["title"]+'</a></h3><p><a href="'+f[c]["url"]+'">\u56f4\u89c2</a><span>'+f[c]["cnt"]+"\u4eba\u6b63\u5728\u6d4f\u89c8</span></p></li>";if(a>4){break}
a++}
k+="</ul>";if(f[6]){var a=1;k+='<ul id="tab-x-2" class="instant-focus-list" style="display:none">';for(var c=6;c<12;c++){if("undefined"==typeof(f[c])){break}
if(temp_doc_doc_id==f[c]["did"]){continue}
h="";var g=d-f[c]["tm"];if(Math.floor(g/60)<60){h=Math.floor(g/60)+"\u5206\u949f\u524d";if(Math.floor(g/60)<1){h="1\u5206\u949f\u524d"}}else{if(Math.floor(g/3600)<24){h=Math.floor(g/3600)+"\u5c0f\u65f6\u524d"}else{h=Math.floor(g/86400)+"\u5929\u524d"}}
k+="<li data-tm="+h+'><a href="'+f[c]["url"]+'" class="pic"><img width="100" height="75" src="'+f[c]["img"]+'" alt="'+f[c]["title"]+'"></a><h3><a href="'+f[c]["url"]+'">'+f[c]["title"]+'</a></h3><p><a href="'+f[c]["url"]+'">\u56f4\u89c2</a><span>'+f[c]["cnt"]+"\u4eba\u6b63\u5728\u6d4f\u89c8</span></p></li>";if(a>4){break}
a++}
k+="</ul>"}
if(f[12]){var a=1;k+='<ul id="tab-x-3" class="instant-focus-list" style="display:none">';for(var c=12;c<18;c++){if("undefined"==typeof(f[c])){break}
if(temp_doc_doc_id==f[c]["did"]){continue}
h="";var g=d-f[c]["tm"];if(Math.floor(g/60)<60){h=Math.floor(g/60)+"\u5206\u949f\u524d";if(Math.floor(g/60)<1){h="1\u5206\u949f\u524d"}}else{if(Math.floor(g/3600)<24){h=Math.floor(g/3600)+"\u5c0f\u65f6\u524d"}else{h=Math.floor(g/86400)+"\u5929\u524d"}}
k+="<li data-tm="+h+'><a href="'+f[c]["url"]+'" class="pic"><img  width="100" height="75" src="'+f[c]["img"]+'" alt="'+f[c]["title"]+'"></a><h3><a href="'+f[c]["url"]+'">'+f[c]["title"]+'</a></h3><p><a href="'+f[c]["url"]+'">\u56f4\u89c2</a><span>'+f[c]["cnt"]+"\u4eba\u6b63\u5728\u6d4f\u89c8</span></p></li>";if(a>4){break}
a++}
k+="</ul>"}
if(k){$("#focus_look_div").html(k)}else{$("#focus_look").hide()}}
var b=0;timer_focus_func=function(){b++;if(b>15){clearInterval(timer3);return}
if($("#focus_look_div").size()<1){return}
clearInterval(timer3)};timer3=setInterval("timer_focus_func()",1000)}
$(".intel-tab_rank>li").mouseover(function(){$(this).siblings().removeClass("hover");$(this).addClass("hover")});function removeHTMLTag(a){a=a.replace(/<\/?[^>]*>/g,"");a=a.replace(/[ | ]*\n/g,"\n");a=a.replace(/&nbsp;/ig,"");return a}
var Zuserid=get_cookie("zol_userid");var Zuserid="undefined"==typeof(Zuserid)?"":Zuserid;var Zsource=2;var Ztitle="undefined"==typeof(temp_doc_title)?document.title:temp_doc_title;var Zcontent=cutString(removeHTMLTag($("#cotent_idd p:eq(0)").html()),200);var Zurl="http://"+location.hostname+location.pathname;var Zpicurl=$("#content-first-img").attr("src");var Zid=temp_doc_doc_id+"-"+temp_doc_class_id;var target="http://icon.zol-img.com.cn/group/js/collectLayer.js";replace_js_src("collect_js",target);var commentTopAd=document.getElementById("commentTopAd");if(commentTopAd){var height2=commentTopAd.offsetHeight;if(height2<20){commentTopAd.style.display="none"}}
$(".fast-nav-bar").live("mouseenter",function(){$("#fast_nav_channel_index").css("display","block")}).live("mouseleave",function(){$("#fast_nav_channel_index").hide()});$(".option-btns .sharebox").click(function(){$(".bds_more").click()});var options_like_hits=0;var options_like_flag=false;var options_btns_tips=null;$(".option-btns .sharebox,.option-btns .likebox,.option-btns .comment-btn").mouseenter(function(){var a=$(this);options_btns_tips=setTimeout(function(){a.children(".btn-tips").show()},800)}).mouseleave(function(){$(this).children(".btn-tips").hide();clearTimeout(options_btns_tips)});$(".option-btns .sharebox").mouseenter(function(){$(this).children(".sharecont").show()}).mouseleave(function(){$(this).children(".sharecont").hide()});$(".option-btns .comment-btn").click(function(){location.hash="add_comment"});$(".option-btns .sharebox .sharecont a,.fixed-share-bar .bdshare_t a").click(function(){var a=$(".option-btns .sharebox .btn");$.ajax({url:"http://dynamic.zol.com.cn/channel/doc_share_like.php?doc_id="+temp_doc_root_id+"&type=1&jsoncallback=?",type:"get",cache:false,dataType:"jsonp",success:function(b){if("success"==b.result){$("#article_share_hits").val(parseInt(parseInt($("#article_share_hits").val()))+1);a.html("\u5206\u4eab\uff08"+parseInt($("#article_share_hits").val())+"\uff09")}}})});$(".option-btns .likebox .btn").click(function(){if(options_like_flag){options_like_hits++;get_hits_tips(options_like_hits);return false}
var a=$(this);$.ajax({url:"http://dynamic.zol.com.cn/channel/doc_share_like.php?doc_id="+temp_doc_root_id+"&class_id="+temp_doc_class_id+"&type=2&jsoncallback=?",type:"get",cache:false,dataType:"jsonp",success:function(b){if("success"==b.result){$("#article_like_hits").val(parseInt(parseInt($("#article_like_hits").val()))+1);a.html("\u5df2\u559c\u6b22\uff08"+parseInt($("#article_like_hits").val())+"\uff09");options_like_flag=true}else{alert("\u60a8\u5df2\u7ecf\u559c\u6b22\u8be5\u6587\u7ae0\u4e86\uff01")}}})});$(document).ready(function(){$.ajax({url:"http://dynamic.zol.com.cn/channel/doc_share_like.php?doc_id="+temp_doc_root_id+"&jsoncallback=?",type:"get",cache:false,dataType:"jsonp",success:function(a){$("#article_share_hits").val(a.share_hits);$("#article_like_hits").val(a.like_hits);if(a.like_hits!=0){$(".option-btns .likebox .btn").html("\u559c\u6b22\uff08"+a.like_hits+"\uff09");if(1==a.is_like){$(".option-btns .likebox .btn").html("\u5df2\u559c\u6b22\uff08"+a.like_hits+"\uff09");options_like_flag=true}}
if(a.share_hits!=0){$(".option-btns .sharebox .btn").html("\u5206\u4eab\uff08"+a.share_hits+"\uff09")}}})});function get_hits_tips(a){var b="";switch(a){case 2:b="\u4eb2\uff0c\u4f60\u5df2\u7ecf\u559c\u6b22\u8fc7\u4e86\uff01";break;case 3:b="\u55ef\u55ef\uff0c\u6211\u4eec\u77e5\u9053\u4f60\u5f88\u559c\u6b22\u5b83\uff01";break;case 4:case 5:b="\u5982\u6b64\u5927\u7231\uff0c\u5c31\u70b9\u65c1\u8fb9\u591a\u8f6c\u53d1\u4e00\u4e0b\u5427\uff01";break;case 6:case 7:b="\u5144\u624d\u5174\u81f4\u9887\u9ad8\uff0c\u4e0d\u59a8\u770b\u770b\u522b\u7684\u6587\u7ae0\u5427\uff01";break;case 8:b="\u8fd8\u5728\u70b9\u554a\uff0c\u7d2f\u4e0d\u7d2f\u554a...";break;case 9:b="\u597d\u5427\uff0c\u65e2\u7136\u5982\u6b64\uff0c\u6765\u804a\u804a\u5929\u5427\uff01";break;case 10:b="\u55ef\uff0c\u6211\u7ed9\u4f60\u4ecb\u7ecd\u4e00\u4e0b\u4e2d\u5173\u6751\u5728\u7ebf\u53d1\u5c55\u53f2\u3002";break;default:b=""}
if(b!=""){alert(b)}}
document.write("<sc"+'ript type="text/javascript" src="http://icon.zol-img.com.cn/public/js/zol_quick_news.js"></scr'+"ipt>");document.write("<sc"+'ript type="text/javascript" src="http://icon.zol-img.com.cn/group/js/login.js"></scr'+"ipt>");document.write("<sc"+'ript type="text/javascript" src="http://icon.zol-img.com.cn/public/js/search.js"></scr'+"ipt>");var _hmt=_hmt||[];$(document).ready(function(){var a=$("#weiboFollowButton").attr(".src");$("#weiboFollowButton").attr("src",a);$("#mobileSoftList_1 img,#mobileSoftList_2 img").picLazyLoad();$("#productRank_1 img,#productRank_2 img,#productRank_3 img,#productRank_4 img").picLazyLoad();$("#dcdvShowPhotoList img").picLazyLoad();$("[data-role=user-login]").zLogin();$("#searchform .skey").zsuggest({offsetX:0,offsetY:5,width:258,source:"article",isSuggest:true});$("#searchform .skey").live("focus",function(){var b="\u641c\u7d22\u5e2e\u5ba2\u6280\u672f\u5e93\u627e\u65b9\u6cd5";var c=$(this).val();if(c==""||c==b){_hmt.push(["_trackEvent","doc:article:zaArtcileSearch:load","load"])}else{_hmt.push(["_trackEvent","doc:article:zaArtcileSearchShow:load","load"])}});$("#zSearchSuggest").live("click",function(){if($("#searchResultList").length>0){_hmt.push(["_trackEvent","doc:article:zaArtcileSearchShow:click","click"])}
if($("#zsearchshow").length>0){_hmt.push(["_trackEvent","doc:article:zaArtcileSearch:click","click"])}})});$(function(){if($("#callWtrend").length!=0){var a="";if(typeof(temp_doc_hardware_id)!="undefined"&&parseInt(temp_doc_hardware_id)>0){a="p"+temp_doc_hardware_id}
$("#callWtrend").wtrendMsg({proId:a,follows:dealer_info_ids_arr})}});var imgReady=(function(){var d=[],a=null,c=function(){var f=0;for(;f<d.length;f++){d[f].end?d.splice(f--,1):d[f]()}!d.length&&b()},b=function(){clearInterval(a);a=null};return function(f,k,n,p,m){var q,g,o,j,l,h=new Image();h.src=f;if(h.complete){}
g=h.width;o=h.height;h.i=k;h.onerror=function(){m&&m.call(h);q.end=true;h=h.onload=h.onerror=null};q=function(){j=h.width;l=h.height;if(j!==g||l!==o||j*l>1024){n.call(h);q.end=true}};q();h.onload=function(){!q.end&&q();p&&p.call(h);h=h.onload=h.onerror=null};if(!q.end){d.push(q);if(a===null){a=setInterval(c,40)}}}})();(function(a){a.fn.articleGallery=function(b){var c=a.extend({thumbNum:5,picObj:null,curIndex:0,slidePic:".slidePicSrc",scrollPic:".scroll-pic ul",prevBtnWrap:".prev-area",prevBtn:".prev-area span",nextBtnWrap:".next-area",nextBtn:".next-area span",scrollPrev:".album .prev-btn",scrollNext:".album .next-btn",textWrap:".title",txtUp:".slide-up",txtDown:".slide-down",txtBox:".gallery-bar",thumbSize:90},b);return this.each(function(){var p="";var m="";var o=c.curIndex;var h=a(this);var u=a(c.slidePic,h);var d=a(c.scrollPic,h);var w=a(c.textWrap,h);var k=a(c.txtUp,h);var r=a(c.txtDown,h);var s=a(c.txtBox,h);var g=d.find("li").length;var j=function(x){var z=u.parent().width();var D=u.parent().height();var A=d.children().eq(x).attr("data-width");var C=d.children().eq(x).attr("data-height");if(A/C>z/D){if(A>z){var B=z;var y=Math.ceil(z*C/A)}else{var B=A;var y=C}}else{if(C>D){var y=D;var B=Math.ceil(A*D/C)}else{var B=A;var y=C}}
u.css({"width":B,"height":y})};var t=function(y){var y=parseInt(y);if(y>=g||y<0){return}
o=y;var A=d.children().eq(y).attr("data-img");var z=A;var x="";var B=d.children().eq(y).attr("data-bigimg");x=d.children().eq(y).find("img").eq(0).attr("alt");w.html(x);u.css("display","none").attr("src","http://icon.zol-img.com.cn/article/slideNew/blank.gif");imgReady(A,1,function(){j(y);u.attr("src",A).fadeIn(500);s.find(".share").attr("data-img",B);_hmt.push(["_trackEvent","cms:article:galleryPicShow:click","click"])});n(y)};var n=function(C){if(c.thumbNum){var D=c.thumbNum}else{var F=arguments[1]?arguments[1]:d.parent().width();var D=Math.ceil(parseInt(F)/c.thumbSize)}
var z=0,A=D;var y=0,E=0;var B=C+1;if(D>=g){y=1;E=g}else{if(B<=Math.ceil(D/2)){y=1;E=D}else{if((g-B)<Math.floor(D/2)){y=g-D+1;E=g}else{y=B+1-Math.ceil(D/2);E=B+Math.floor(D/2)}}}
z=y-1;A=E-1;d.children().removeClass("current hover").eq(C).addClass("current");var x=z*c.thumbSize;d.css({"margin-left":"-"+x+"px"});q(z,A,C)};var q=function(z,y,x){d.children().each(function(B){if(B>=z&&B<=y){var A=a(this).find("img").eq(0);if(!A.attr("src")&&A.attr(".src")){A.attr("src",A.attr(".src"))}}});setTimeout(function(){for(var C=z;C<=y;C++){var A=new Image();var B=d.children().eq(x);A.src=B.attr("data-img")}},1000)};var f=function(){var x=-40;r.on("click",function(){s.animate({"bottom":x},300);k.animate({"bottom":0},300)});k.on("click",function(){s.animate({"bottom":0},300);k.animate({"bottom":x},300)})};var v=function(){a(c.prevBtnWrap,h).hover(function(){a(c.prevBtn,h).show()},function(){a(c.prevBtn,h).hide()});a(c.nextBtnWrap,h).hover(function(){a(c.nextBtn,h).show()},function(){a(c.nextBtn,h).hide()})};var l=function(){a(c.prevBtnWrap,h).click(function(){t(o-1)});a(c.prevBtn,h).click(function(){t(o-1);return false});a(c.scrollPrev,h).click(function(){t(o-1)});a(c.nextBtnWrap,h).click(function(){t(o+1)});a(c.nextBtn,h).click(function(){t(o+1);return false});a(c.scrollNext,h).click(function(){t(o+1)})};t(0);d.on("click","li",function(){var y=a(this);var x=y.attr("data-index");t(x)});v();l();f()})}}(jQuery));$(function(){var a=$(".group-picture");if(a.length>0){_hmt.push(["_trackEvent","cms:article:galleryShare:load","load"]);_hmt.push(["_trackEvent","cms:article:galleryPicShow:load","load"]);a.articleGallery();a.find(".scroll-pic li").hover(function(){$(this).addClass("hover")},function(){$(this).removeClass("hover")});if(typeof(temp_doc_hardware_id)!="undefined"&&temp_doc_hardware_id){if(typeof(temp_doc_hardware_url)!="undefined"&&temp_doc_hardware_url){a.find("a.detail").attr("href",temp_doc_hardware_url).css({"display":"inline"})}}
var b=a.find(".share");b.click(function(){var c=$(this).attr("data-img");if("undefined"!=typeof(bdShare)){if(bdShare.fn&&bdShare.fn.init){bds_config.bdPic=c;bdShare.fn.init()}}
$(".fixed-share-bar .bds_more").trigger("click");_hmt.push(["_trackEvent","cms:article:galleryShare:click","click"])})}});